#!/bin/sh

echo -n "Searching for LRS..."
LRS=`which lrs 2> /dev/null`
if [ -z "${LRS}" ]; then
	LRS=`which glrs 2> /dev/null`
fi

if [ -z "${LRS}" ]; then
	echo "not found!"
	exit 1;
fi

echo "${LRS}"

INFILE=$1
OUTDIR=${1%.txt}-mux-results

# create lrs-input-files
echo "Generating LRS input..."
swipl -q -g main -s mux-setup.pl -- ${INFILE}

# create working directory and move .ine files and relevant scripts into it
mkdir $OUTDIR

# go to working directory, run lrs on all files
FILES=`ls *.ine`
for LRSIN in $FILES; do
	LRSOUT=${LRSIN%ine}out
	echo "Invoking LRS on ${LRSIN}...";
	${LRS} ${LRSIN} ${LRSOUT}
done


# run interpretation on all files
INTERP_FILES=`ls *.out`
for INFILE in ${INTERP_FILES}; do
	g=${INFILE%.out}
	swipl -q -g main -s mux-interpretation.pl -- $g
done

# tidy up
rm *.ine
rm *.constraints
rm *.out

# stash results
mv *.mux $OUTDIR
